<a href="https://colab.research.google.com/github/snehabhut/trial/blob/master/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


In [8]:
np.__version__

'1.18.5'

In [23]:
import numpy as np


A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A,B,C,D]):
  print(f'{name} {np.all(array)}')

A True
B False
C False
D True


In [28]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
for name, array in zip(list('ABC'), [A,B,C]):
  print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


In [30]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
for name, array in zip(list('ABCD'), [A,B,C,D]):
  print(f'{name} {np.any(array, axis=0)}')

A [False False False]
B [False  True False]
C [ True False False]
D [ True False]


In [31]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
np.isnan([A])

array([[[False, False, False,  True],
        [False,  True, False, False]]])

In [32]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
np.allclose(A,B)

True

In [35]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
#A==B
np.equal(A,B)

array([False, False,  True])

In [36]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
#A>B
np.greater(A,B)

array([ True, False, False, False])

In [38]:
np.zeros(shape=(4,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
np.full(shape=(10,10), fill_value=225, dtype='float')

array([[225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.]])

In [43]:
np.ones(shape=(10,10),dtype='float')*225

array([[225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.],
       [225., 225., 225., 225., 225., 225., 225., 225., 225., 225.]])